[project]
name = "nemiro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "passlib[argon2]>=1.7.4",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pyjwt>=2.13.0",
    "passlib>=1.7.4",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.54",
    "uuid6>=2025.0.1",
]
